name: Fetch and Upload TMart Orders

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:     # Manual trigger

jobs:
  run-fetcher:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Decode and save credentials
        env:
          CREDENTIALS_JSON: ${{ secrets.GMAIL_CREDENTIALS }}
          TOKEN_JSON: ${{ secrets.GMAIL_TOKEN }}
        run: |
          echo "$CREDENTIALS_JSON" > credentials.json
          echo "$TOKEN_JSON" > token.json

      - name: Run Gmail Fetcher
        run: python gmail_attachment_fetcher.py
